name: list details of the workflow
on:
    issues:
        types: [opened, edited, deleted]
    workflow_dispatch:
jobs:
    list:
        runs-on: ubuntu-latest
        steps:
            - name: list details
              run: echo "${{ toJson(github) }}"